[application]
  default_platform = "web"
  name             = "presentation_frontend"

[web.app]
  title = "IVKIK"

[web.watcher]

[bundle]
  icon       = ["assets/dioxus.png"]
  identifier = "com.mingyuchoo.ivkik"
  publisher  = "IVKIK"
  resources  = ["assets/*"]
