[workspace]
  default-members = ["crates/hello-world"]
  members         = ["crates/hello-world"]
  resolver        = "2"

  [workspace.dependencies]
    anyhow         = "1.0.104"
    gpui           = {package = "gpui-pre", version = "=0.3.7"}
    gpui-component = "0.7.0"
    gpui-platform  = {package = "gpui-pre-platform", version = "=0.3.7", features = ["font-kit", "wayland", "x11"]}
