[workspace]
members = [
    "crates/p2p_core",
    "crates/p2p_infra",
    "crates/p2p_app",
    "crates/p2p_runtime",
    "crates/p2p_gui",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
p2p_core = { path = "crates/p2p_core" }
p2p_app = { path = "crates/p2p_app" }
p2p_infra = { path = "crates/p2p_infra" }
p2p_runtime = { path = "crates/p2p_runtime" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
async-trait = "0.1"
tokio = { version = "1.38", features = ["rt", "macros", "sync", "time", "net"] }
async-channel = "2"
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls-ring"] }
rustls = { version = "0.23", default-features = false, features = ["std", "ring"] }
rcgen = { version = "0.14", default-features = false, features = ["crypto", "ring"] }
sha2 = "0.10"
dirs = "5"
tempfile = "3"
socket2 = { version = "0.5", features = ["all"] }
gpui = { version = "0.2.2", features = ["runtime_shaders"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
unicode-segmentation = "1.13"

[patch.crates-io]
block = { path = "vendor/block" }
proc-macro-error2 = { path = "vendor/proc-macro-error2" }
