networks:
  docker-link:
    external: true

services:
  backend:
    image: azure-bicep-rust-app/backend:latest
    container_name: backend
    command: ["./target/release/backend", "--port", "8080"]
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - docker-link
    volumes:
      - ../backend/wwwroot:/app/wwwroot:ro
    restart: unless-stopped
