[workspace]
  members = [
    "crates/proto",
    "crates/server",
    "crates/client",
    "crates/web",
    "crates/tests",
  ]
  resolver = "2"

  [workspace.package]
    authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
    edition = "2024"
    version = "0.1.0"

  [workspace.dependencies]
    anyhow             = "1.0.102"
    axum               = "0.8.9"
    prost              = "0.14.3"
    serde              = {features = ["derive"], version = "1.0.229"}
    serde_json         = "1.0.151"
    thiserror          = "2.0.18"
    tokio              = {features = ["macros", "rt-multi-thread", "time"], version = "1.50.0"}
    tonic              = "0.14.5"
    tonic-build        = "0.14.5"
    tonic-health       = "0.14.5"
    tonic-prost        = "0.14.5"
    tonic-prost-build  = "0.14.5"
    tower              = "0.5.2"
    tower-http         = {features = ["cors", "trace"], version = "0.7.1"}
    tracing            = "0.1.44"
    tracing-subscriber = "0.3.22"

[profile.dev]
  codegen-units = 256
  debug         = true
  incremental   = true
  opt-level     = 1

[profile.release]
  codegen-units = 1
  debug         = false
  lto           = "thin"
  opt-level     = 3
