[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[tasks.clippy]
  args    = ["clippy"]
  command = "cargo"

[tasks.check]
  args    = ["check"]
  command = "cargo"

[tasks.format]
  args          = ["fmt"]
  command       = "cargo"
  dependencies  = ["check", "clippy"]
  install_crate = "rustfmt"

[tasks.build]
  args         = ["build", "--profile", "dev"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release]
  args         = ["build", "--profile", "release"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.watch-run]
  # `cargo install cargo-watch`로 설치
  args          = ["watch", "-x", "run"]
  command       = "cargo"
  dependencies  = ["format"]
  install_crate = "cargo-watch"

[tasks.run]
  args         = ["run"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.run-with-swagger]
  script = '''
    echo "Starting server with Swagger UI..."
    echo "Swagger UI will be available at: http://localhost:8080/swagger-ui/"
    cargo run
  '''
  dependencies = ["format"]
