[package]
  edition = "2024"
  name    = "egui-surreal"
  version = "0.1.0"

[dependencies]
  anyhow      = "1.0.100"
  async-trait = "0.1.83"
  eframe      = "0.35.0"
  egui        = "0.35.0"
  faker_rand  = "0.1.1"
  rand        = "0.8.5"
  serde       = {version = "1.0.228", features = ["derive"]}
  serde_json  = "1.0.145"
  surrealdb   = "2.3.10"
  tokio       = {version = "1.47.1", features = ["full"]}
