[package]
  edition = "2024"
  name    = "window-app"
  publish = false
  version = "0.1.0"

[[bin]]
  name = "window-app"
  path = "src/main.rs"

[dependencies]
  anyhow.workspace         = true
  gpui.workspace           = true
  gpui-component.workspace = true
  gpui-platform.workspace  = true
  rust-embed.workspace     = true
