//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "input_indices")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub target_value: Option<f64>,
    pub actual_value: Option<f64>,
    pub weight: Option<f64>,
    pub performance_indicator_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::performance_indicators::Entity",
        from = "Column::PerformanceIndicatorId",
        to = "super::performance_indicators::Column::Id"
    )]
    PerformanceIndicator,
}

impl Related<super::performance_indicators::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerformanceIndicator.def()
    }
}
