//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "performance_indicators")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub year: i32,
    pub target_value: Option<f64>,
    pub actual_value: Option<f64>,
    pub unit: Option<String>,
    pub status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::input_indices::Entity")]
    InputIndices,
    #[sea_orm(has_many = "super::process_indices::Entity")]
    ProcessIndices,
    #[sea_orm(has_many = "super::output_indices::Entity")]
    OutputIndices,
    #[sea_orm(has_many = "super::outcome_indices::Entity")]
    OutcomeIndices,
}

impl Related<super::input_indices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InputIndices.def()
    }
}

impl Related<super::process_indices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProcessIndices.def()
    }
}

impl Related<super::output_indices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OutputIndices.def()
    }
}

impl Related<super::outcome_indices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OutcomeIndices.def()
    }
}
