//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
pub use super::input_indices::Entity as InputIndices;
pub use super::outcome_indices::Entity as OutcomeIndices;
pub use super::output_indices::Entity as OutputIndices;
pub use super::performance_indicators::Entity as PerformanceIndicators;
pub use super::process_indices::Entity as ProcessIndices;
pub use super::users::Entity as Users;
