[package]
  authors.workspace = true
  edition.workspace = true
  name              = "proto"
  version.workspace = true

[dependencies]
  prost.workspace       = true
  tonic.workspace       = true
  tonic-prost.workspace = true

[build-dependencies]
  tonic-build.workspace       = true
  tonic-prost-build.workspace = true
