/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOpenApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSpecs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** @description Replays in-memory history for the run and then streams new control-plane events. */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFunctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/functions/{id}/{resource}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                resource: "requirements" | "rules" | "behaviors" | "scenarios" | "decisions" | "evidence" | "certificate";
            };
            cookie?: never;
        };
        get: operations["getFunctionResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Record a HITL decision. The decider is the verified `sub` of the OIDC bearer token; when
         *     `AMAP_OIDC_REVIEWER_ROLE` is configured the token must carry that role in the configured
         *     roles claim. Cedar governance (`decide_review`) is evaluated before the decision is stored.
         */
        post: operations["decideReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queryEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph.dot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getKnowledgeGraphDot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Durable, append-only ledger of LLM calls (newest first). Shared with a standalone
         *     llm-gateway when both services use the same database.
         */
        get: operations["getLlmAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Priority: "P0" | "P1" | "P2" | "P3";
        SpecSummary: {
            path: string;
            function_id: string;
            name: string;
            domain: string;
            priority: components["schemas"]["Priority"];
            description: string;
            mock_available: boolean;
        };
        StartRunRequest: {
            spec: string;
            /** @default false */
            mock: boolean;
        };
        WorkflowRun: {
            id: string;
            function_id: string;
            /** @enum {string} */
            status: "running" | "halted" | "certified" | "failed" | "error";
            spec_path: string;
            mock: boolean;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            updated_at: string;
            outcome?: components["schemas"]["WorkflowOutcome"] | components["schemas"]["ErrorOutcome"] | null;
            checkpoint: {
                [key: string]: unknown;
            };
        };
        BusinessFunction: {
            id: string;
            name: string;
            domain: string;
            priority: components["schemas"]["Priority"];
            description: string;
        };
        /** @enum {string} */
        ReviewStatus: "pending" | "approved" | "rejected";
        /** @enum {string} */
        HitlTier: "auto" | "ai_cross_review" | "expert_review" | "sme_mandatory";
        ReviewRequest: {
            id: string;
            run_id?: string | null;
            function_id: string;
            tier: components["schemas"]["HitlTier"];
            reason: string;
            /** Format: double */
            uncertainty: number;
            status: components["schemas"]["ReviewStatus"];
            /** Format: date-time */
            requested_at: string;
            /** @description Verified OIDC subject of the decider, or the automation that decided. */
            decided_by?: string | null;
            /** @description `oidc:<issuer>`, `auto_approve_hitl`, or `insecure-dev-header`. */
            decided_via?: string | null;
            /** Format: date-time */
            decided_at?: string | null;
        };
        LlmAuditEntry: {
            audit_id: string;
            content_hash: string;
            /** Format: date-time */
            at: string;
            run_id?: string | null;
            role: string;
            task: string;
            prompt_version: string;
            provider: string;
            model: string;
            input_tokens: number;
            output_tokens: number;
            cached: boolean;
            /** Format: double */
            cost_usd: number;
            request_hash: string;
            pii_masked: boolean;
        };
        ReviewDecision: {
            /** @enum {string} */
            status: "approved" | "rejected";
        };
        ControlEvent: {
            subject: string;
            run_id: string;
            function_id: string;
            payload: unknown;
            /** Format: date-time */
            at: string;
        };
        /** @enum {string} */
        StepStatus: "succeeded" | "failed" | "halted" | "skipped";
        StepReport: {
            name: string;
            role: string;
            status: components["schemas"]["StepStatus"];
            attempts: number;
            summary: string;
            duration_ms: number;
        };
        RunReport: {
            run_id: string;
            function_id: string;
            steps: components["schemas"]["StepReport"][];
            outputs: {
                [key: string]: unknown;
            };
            halted?: string | null;
            failed?: string | null;
        };
        GateCheck: {
            kpi: string;
            required: string;
            actual: string;
            passed: boolean;
        };
        GateReport: {
            function_id: string;
            certified: boolean;
            checks: components["schemas"]["GateCheck"][];
        };
        WorkflowOutcome: {
            reports: components["schemas"]["RunReport"][];
            certified: boolean;
            gate?: components["schemas"]["GateReport"] | null;
            iterations: number;
            halted?: string | null;
            failed?: string | null;
            final_outputs: {
                [key: string]: unknown;
            };
        };
        ErrorOutcome: {
            error: string;
        };
    };
    responses: {
        /** @description Request failed. */
        TextError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: {
        /** @description Self-declared actor name. Trusted only in insecure development mode. */
        Actor: string;
        RunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getOpenApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This OpenAPI contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    listSpecs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run specifications available beneath the configured specification root. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecSummary"][];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Known workflow runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"][];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description Self-declared actor name. Trusted only in insecure development mode. */
                "X-AMAP-Actor"?: components["parameters"]["Actor"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description The newly started run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            400: components["responses"]["TextError"];
            403: components["responses"]["TextError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow run state, checkpoint, and final outcome when complete. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            404: components["responses"]["TextError"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream. Each data field is a serialized ControlEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["TextError"];
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description Self-declared actor name. Trusted only in insecure development mode. */
                "X-AMAP-Actor"?: components["parameters"]["Actor"];
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resumed run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            404: components["responses"]["TextError"];
            409: components["responses"]["TextError"];
        };
    };
    listFunctions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovered business functions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessFunction"][];
                };
            };
        };
    };
    getFunctionResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                resource: "requirements" | "rules" | "behaviors" | "scenarios" | "decisions" | "evidence" | "certificate";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requested function resource. Shape depends on the resource parameter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            404: components["responses"]["TextError"];
        };
    };
    listReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human review requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRequest"][];
                };
            };
        };
    };
    decideReview: {
        parameters: {
            query?: never;
            header?: {
                /** @description Self-declared actor name. Trusted only in insecure development mode. */
                "X-AMAP-Actor"?: components["parameters"]["Actor"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Decision recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        decided_by?: string;
                        decided_via?: string;
                        ok: boolean;
                    };
                };
            };
            400: components["responses"]["TextError"];
            404: components["responses"]["TextError"];
        };
    };
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description In-memory event history for all runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlEvent"][];
                };
            };
        };
    };
    queryEvidence: {
        parameters: {
            query: {
                sql: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rows returned by a read-only DataFusion SELECT query. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            400: components["responses"]["TextError"];
        };
    };
    getKnowledgeGraphDot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current knowledge graph in Graphviz DOT format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getLlmAudit: {
        parameters: {
            query?: {
                run_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LLM audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmAuditEntry"][];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
