[build]
  dist   = "dist"
  target = "index.html"

[serve]
  addresses = ["127.0.0.1"]
  port      = 1420

[tools]
  wasm-bindgen = "0.2"

  [build.rust]
    cargo-args = ["-p", "presentation_frontend"]
