[package]
name = "p2p_gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "p2p-gui"
path = "src/main.rs"

[dependencies]
p2p_core.workspace = true
p2p_app.workspace = true
p2p_runtime.workspace = true
gpui.workspace = true
async-channel.workspace = true
chrono.workspace = true
unicode-segmentation.workspace = true
